name: odd-pi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - numpy
  - jupyter
  - polars
  - matplotlib
  - paramiko
  - pip
  - pip:
    - cvu-python
    - nbdev

