name: odd-pi
channels:
  - defaults
  - conda-forge
  - fastai
dependencies:
  - python=3.10
  - numpy
  - jupyter
  - polars
  - matplotlib
  - paramiko
  - discord.py
  - rich
  - typer-cli
  - pip
  - pip:
    - cvu-python
    - nest_asyncio
    - nbdev
    - python-dotenv
    - opencv-python==4.5.5.64
    - onnxruntime
    - cryptography==36.0.2
