# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/odd-pi',
                'doc_host': 'https://jvivian.github.io',
                'git_url': 'https://github.com/jvivian/odd-pi',
                'lib_path': 'odd_pi'},
  'syms': { 'odd_pi.core': { 'odd_pi.core._connect': ('core.html#_connect', 'odd_pi/core.py'),
                             'odd_pi.core._fetch': ('core.html#_fetch', 'odd_pi/core.py'),
                             'odd_pi.core.capture_and_fetch': ('core.html#capture_and_fetch', 'odd_pi/core.py'),
                             'odd_pi.core.get_default_model': ('core.html#get_default_model', 'odd_pi/core.py'),
                             'odd_pi.core.pltimg': ('core.html#pltimg', 'odd_pi/core.py'),
                             'odd_pi.core.predict': ('core.html#predict', 'odd_pi/core.py'),
                             'odd_pi.core.run_bot': ('core.html#run_bot', 'odd_pi/core.py')}}}
