# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/odd-pi',
                'doc_host': 'https://jvivian.github.io',
                'git_url': 'https://github.com/jvivian/odd-pi',
                'lib_path': 'odd_pi'},
  'syms': {'odd_pi.core': {'odd_pi.core.foo': ('core.html#foo', 'odd_pi/core.py')}}}
